/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#eef2f6",
        error: "#ba1a1a",
        error_container: "#ffdad6",
        inverse_on_surface: "#f0f1f2",
        inverse_primary: "#c3c0ff",
        inverse_surface: "#2e3132",
        on_background: "#191c1d",
        on_error: "#ffffff",
        on_error_container: "#93000a",
        on_primary: "#ffffff",
        on_primary_container: "#dad7ff",
        on_primary_fixed: "#0f0069",
        on_primary_fixed_variant: "#3323cc",
        on_secondary: "#ffffff",
        on_secondary_container: "#fffbff",
        on_secondary_fixed: "#25005a",
        on_secondary_fixed_variant: "#5a00c6",
        on_surface: "#191c1d",
        on_surface_variant: "#404759",
        on_tertiary: "#ffffff",
        on_tertiary_container: "#93e8ff",
        on_tertiary_fixed: "#001f26",
        on_tertiary_fixed_variant: "#004e5c",
        outline: "#5f6776",
        outline_variant: "#aeb7c4",
        primary: "#3525cd",
        primary_container: "#4f46e5",
        primary_fixed: "#e2dfff",
        primary_fixed_dim: "#c3c0ff",
        secondary: "#712ae2",
        secondary_container: "#8a4cfc",
        secondary_fixed: "#eaddff",
        secondary_fixed_dim: "#d2bbff",
        surface: "#f3f5f8",
        surface_bright: "#fbfcfe",
        surface_container: "#e6ebf0",
        surface_container_high: "#e0e5eb",
        surface_container_highest: "#d8dde5",
        surface_container_low: "#ecf0f4",
        surface_container_lowest: "#ffffff",
        surface_dim: "#cfd6de",
        surface_tint: "#4d44e3",
        surface_variant: "#dfe4ea",
        tertiary: "#00505f",
        tertiary_container: "#006a7c",
        tertiary_fixed: "#acedff",
        tertiary_fixed_dim: "#4cd7f6"
      },
      fontFamily: {
        heading: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        'ambient': '0 28px 56px 0 rgba(25, 28, 29, 0.08)',
        'ambient-sm': '0 14px 32px 0 rgba(25, 28, 29, 0.08)',
      }
    },
  },
  plugins: [],
}
